[env:esp32s3]
platform = espressif32
board = adafruit_metro_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Libraries
lib_deps =
    miguelbalboa/MFRC522@^1.4.10

; Build flags
build_flags = 
    -D CORE_DEBUG_LEVEL=4

; Serial monitor
monitor_port = COM5
upload_port = COM5

; Upload via Serial/USB
upload_protocol = esptool
upload_flags = 
    --before=default_reset
    --after=hard_reset
    