[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 9600
upload_speed = 921600

upload_protocol = esptool
upload_port = COM7
monitor_port = COM7

; Libraries
lib_deps =
    miguelbalboa/MFRC522@^1.4.10
    bblanchon/ArduinoJson@^7.0.0

; Debug
build_flags = 
    -D CORE_DEBUG_LEVEL=4
    